name: Go Submodule CI - app-scanner

on:
  push:
    branches: [ main ] # Or your default branch
  pull_request:
    branches: [ main ] # Or your default branch

jobs:
  test-and-lint:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20' # From go.mod
          cache: true

      - name: Install Dependencies
        run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54.2  # Using a version known to work with Go 1.20
          args: --timeout=5m

      - name: Test
        run: go test -v -race ./... # Assuming standard tests exist

      - name: Send repository_dispatch to Sirius main repo
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.MAIN_REPO_ACCESS_TOKEN }}
          repository: SiriusScan/Sirius
          event-type: submodule-update
          client-payload: '{ "submodule": "${{ github.repository }}", "commit_sha": "${{ github.sha }}", "ref": "${{ github.ref }}" }' 